### ISSUE TITLE
Intermittent failure of tests

### ISSUE THREAD

**Issue by JSAssassin** [w3c/vc-bitstring-status-list-test-suite#25]
Tests https://github.com/w3c-ccg/status-list-2021-test-suite/blob/main/tests/20-verify.js#L94 and https://github.com/w3c-ccg/status-list-2021-test-suite/blob/main/tests/20-verify.js#L124 experience intermittent failures for DB.

Behavior: 

The assertion for the revoked/suspended VC status sometimes fails because, in some cases, the status remains unchanged after the update.
Other times, the status is updated to `true`, but the `shouldFailVerification` assertions fail due to inconsistencies in the response, where it sometimes contain a result and sometimes lacks error data.

Note:

The tests pass successfully when using localhost endpoints on the main branch for both the issuer and verifier services (v20.1.2 and v16.1.2, respectively). So, I am unable to replicate the problem locally. 

Also tried creating new QA DB issuer and verifier instances (https://github.com/w3c-ccg/vc-api-test-suite-implementations/compare/update-db-status-list-implementation) that uses the latest versions of issuer and verifier(v20.1.2 and v16.1.2), that didn't fix the issue though.

**Comment by BigBlueHat** [comment]
This should be resolved.
