### ISSUE TITLE
Rename test suite & tag to align with the change in spec name.

### ISSUE THREAD

**Issue by JSAssassin** [w3c/vc-bitstring-status-list-test-suite#26]

**Comment by BigBlueHat** [comment]
This repo also needs to move (after renaming) to the W3C org next to it's spec: https://github.com/w3c/vc-bitstring-status-list

**Comment by aljones15** [comment]
repo has been renamed, but test suite title needs updating etc.

vc-bitstring-status-list-test-suite

**Comment by aljones15** [comment]
this PR contains a work item for this feature: https://github.com/w3c-ccg/vc-test-suite-implementations/pull/99#pullrequestreview-1957705000

We need to provision VC 2.0 endpoints for this test suite.

**Comment by aljones15** [comment]
the new tag for the endpoints is `BitstringStatusList`
