### ISSUE TITLE
Add future test suite endpoints to w3c's implementation package

### ISSUE THREAD

**Issue by aljones15** [w3c/vc-bitstring-status-list-test-suite#35]
Endpoints for this test suite we originally in the other w3c-ccg implementations repo here: https://github.com/w3c-ccg/vc-test-suite-implementations/blob/main/implementations/

1. this suite should use the w3c's implementations package here: https://github.com/w3c/vc-test-suite-implementations
2. those endpoints will need use the updated tag for this test suite
3. those endpoints will need to be VC 2.0 backwards compatible
4. the README will need to update in both the w3c's implementations lib and here to reflect the changes.

**Comment by BigBlueHat** [comment]
All done.
